---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [19]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [20]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [21]:
def answer_one():
    return df['Gold'].argmax()                    #    (df[df['Gold']==(df['Gold']).max()]).index[0]   
answer_one()


'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [22]:
def answer_two():
    return (abs(df['Gold']-df['Gold.1'])).argmax()      #  (df[(df['Gold']-df['Gold.1'])==(df['Gold']-df['Gold.1']).max()]).index[0]
answer_two()


'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [23]:
df[(df['Gold.1']>1) & (df['Gold.2']>1)].head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  Silver.1  \
Australia        25   139     152     177    468        18       5         3   
Austria          26    18      33      35     86        22      59        78   
Belarus           5    12      24      39     75         6       6         4   
Canada           25    59      99     121    279        22      62        56   
China             9   201     146     126    473        10      12        22   

           Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Australia         4       12       43     144       155       181   
Austria          81      218       48      77       111       116   
Belarus           5       15       11      18        28        44   
Canada           52      170       47     121       155       173   
China            19       53       19     213       168       145   

           Combined total   ID  
Australia             480  AUS  
Austria               304  AUT  
Belarus                90  BLR  
Canada                449  CAN  
China                 526  CHN

In [24]:
def answer_three():
    only_gold=df[(df['Gold.1'] > 1) & (df['Gold'] >1)]
    only_gold["Difference"]=(abs(only_gold['Gold'] - only_gold['Gold.1']))/only_gold['Gold.2']
    return only_gold["Difference"].argmax()
answer_three()

'Australia'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [25]:
def answer_four():
    df['Points']=3*(df['Gold.2'])+2*(df['Silver.2'])+df['Bronze.2']
    return df['Points']
answer_four()

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            923
Austria                              569
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              154
Belgium                              276
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             411
Burundi                                3
Cameroon                              12
Canada                               846
Chile                                 24
China                               1120
Colombia        

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [26]:
census_df = pd.read_csv('census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [70]:
def answer_five():
    df=census_df[census_df['SUMLEV'] == 50]
    df = df.groupby( [ "SUMLEV", "STNAME"] ).size().to_frame(name = 'count').reset_index()
    return df.loc[df['count'].idxmax()]['STNAME']
    #     return (census_df.where(census_df['COUNTY']==census_df['COUNTY'].max())).dropna()[['CTYNAME']]

answer_five()

'Texas'

In [89]:
census_df.groupby( [ "SUMLEV", "STNAME"] ).size().to_frame(name='Harshit').head()

Harshit
SUMLEV STNAME             
40     Alabama           1
       Alaska            1
       Arizona           1
       Arkansas          1
       California        1

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [88]:
def answer_six():
    return census_df[['CENSUS2010POP','STNAME']].sort("CENSUS2010POP",ascending=False).head(3)
answer_six()

CENSUS2010POP      STNAME
190        37253956  California
2566       25145561       Texas
1860       19378102    New York

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [153]:
def answer_seven():
    df=census_df[census_df['SUMLEV'] == 50]
    df['STDEV'] = df[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012',
                      'POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].std(axis=1)
    return df.loc[df['STDEV'].idxmax()]['CTYNAME']
answer_seven()

'Harris County'

In [152]:
    df=census_df[census_df['SUMLEV'] == 50]
    df['STDEV'] = df[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012',
                      'POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].std(axis=1)
    df['STDEV'].idxmax()

2667

In [154]:
hars=census_df.iloc[[(abs(census_df['POPESTIMATE2010']-census_df['POPESTIMATE2015']).argmax())]]
hars[['STNAME']]

STNAME
2566  Texas

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [159]:
def answer_eight():
    df=census_df[census_df['SUMLEV'] == 50]
    county_name = df['CTYNAME'].str.startswith('Washington')
    pop_estim = df['POPESTIMATE2015'] > df['POPESTIMATE2014']
    df = df[((df['REGION'] == 1) | (df['REGION'] == 2)) & county_name & pop_estim]
    return df[['STNAME', 'CTYNAME']]
answer_eight()

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [156]:
df2=census_df[census_df['POPESTIMATE2015']>census_df['POPESTIMATE2014']]
df2

SUMLEV  REGION  DIVISION  STATE  COUNTY     STNAME             CTYNAME  \
0         40       3         6      1       0    Alabama             Alabama   
1         50       3         6      1       1    Alabama      Autauga County   
2         50       3         6      1       3    Alabama      Baldwin County   
4         50       3         6      1       7    Alabama         Bibb County   
5         50       3         6      1       9    Alabama       Blount County   
9         50       3         6      1      17    Alabama     Chambers County   
11        50       3         6      1      21    Alabama      Chilton County   
14        50       3         6      1      27    Alabama         Clay County   
16        50       3         6      1      31    Alabama       Coffee County   
18        50       3         6      1      35    Alabama      Conecuh County   
21        50       3         6      1      41    Alabama     Crenshaw County   
22        50       3         6      1      43    Alabama      Cullman County   
23        50       3         6      1      45    Alabama         Dale County   
25        50       3         6      1      49    Alabama       DeKalb County   
26        50       3         6      1      51    Alabama       Elmore County   
27        50       3         6      1      53    Alabama     Escambia County   
30        50       3         6      1      59    Alabama     Franklin County   
31        50       3         6      1      61    Alabama       Geneva County   
34        50       3         6      1      67    Alabama        Henry County   
35        50       3         6      1      69    Alabama      Houston County   
41        50       3         6      1      81    Alabama          Lee County   
42        50       3         6      1      83    Alabama    Limestone County   
45        50       3         6      1      89    Alabama      Madison County   
48        50       3         6      1      95    Alabama     Marshall County   
49        50       3         6      1      97    Alabama       Mobile County   
51        50       3         6      1     101    Alabama   Montgomery County   
54        50       3         6      1     107    Alabama      Pickens County   
56        50       3         6      1     111    Alabama     Randolph County   
58        50       3         6      1     115    Alabama    St. Clair County   
59        50       3         6      1     117    Alabama       Shelby County   
...      ...     ...       ...    ...     ...        ...                 ...   
3136      50       2         3     55      78  Wisconsin    Menominee County   
3138      50       2         3     55      81  Wisconsin       Monroe County   
3140      50       2         3     55      85  Wisconsin       Oneida County   
3141      50       2         3     55      87  Wisconsin    Outagamie County   
3142      50       2         3     55      89  Wisconsin      Ozaukee County   
3148      50       2         3     55     101  Wisconsin       Racine County   
3150      50       2         3     55     105  Wisconsin         Rock County   
3152      50       2         3     55     109  Wisconsin    St. Croix County   
3153      50       2         3     55     111  Wisconsin         Sauk County   
3156      50       2         3     55     117  Wisconsin    Sheboygan County   
3158      50       2         3     55     121  Wisconsin  Trempealeau County   
3159      50       2         3     55     123  Wisconsin       Vernon County   
3163      50       2         3     55     131  Wisconsin   Washington County   
3164      50       2         3     55     133  Wisconsin     Waukesha County   
3169      40       4         8     56       0    Wyoming             Wyoming   
3170      50       4         8     56       1    Wyoming       Albany County   
3171      50       4         8     56       3    Wyoming     Big Horn County   
3172      50       4         8     56       5    Wyoming     Campbell County   
3174  